#!/bin/bash

# active-workspace
# script follows each modification of active-tag file
# created by awesomewm and supplies it continously to
# eww workspace widget

followed_log="$HOME/.cache/awesomewm/$1-active-tag"
while inotifywait -qq -e modify "$followed_log"; do
  echo $(cat $followed_log)
done
