#!/bin/bash

# workspaces
# script follows each modification of tag-overview
# file created by awesomewm and supplies it continously
# to eww workspace widget

function output_data () {
  followed_log="$HOME/.cache/awesomewm/tag-overview"

  json=$(cat $followed_log)
  echo $json \
    | jq .display \
    | jq ".[] | select(.id == $1)" \
    | jq .workspaces -c
}

output_data $1

while inotifywait -qq -e modify "$followed_log"; do
  output_data $1
done
