#!/bin/bash

# workspaces
# script follows each modification of tag-overview
# file created by awesomewm and supplies it continously
# to eww workspace widget

followed_log="$HOME/.cache/awesomewm/tag-overview"
while inotifywait -qq -e modify "$followed_log"; do
  json=$(cat $followed_log)
  echo $json \
    | jq .display \
    | jq ".[] | select(.id == $1)" \
    | jq .workspaces -c
done
